<script type="text/javascript">
//<![CDATA[
    var MSG_DT_FIRST = _("Primero");
    var MSG_DT_LAST = _("Último");
    var MSG_DT_NEXT = _("Siguiente");
    var MSG_DT_PREVIOUS = _("Anteriores");
    var MSG_DT_EMPTY_TABLE = _("No hay datos disponibles en la tabla");
    var MSG_DT_INFO = _("Mostrando _START_ a _END_ de _TOTAL_ ");
    var MSG_DT_INFO_EMPTY = _("No hay entradas para mostrar");
    var MSG_DT_INFO_FILTERED = _("(filtrado desde _MAX_ entradas totales)");
    var MSG_DT_LENGTH_MENU = _("Mostrar entradas _MENU_ ");
    var MSG_DT_LOADING_RECORDS = _("Cargando");
    var MSG_DT_PROCESSING = _("Procesando...");
    var MSG_DT_SEARCH = _("Buscar:");
    var MSG_DT_ZERO_RECORDS = _("No se encontraron registros coincidentes");
//]]>
</script>
