<ul id="navigation">
 <li> <a href="/cgi-bin/koha/cataloguing/addbiblio.pl?biblionumber=[% biblionumber %]">Editar registro bibliográfico</a></li>
 <li> <a href="/cgi-bin/koha/catalogue/detail.pl?biblionumber=[% biblionumber %]">Vista normal</a></li>
 <li> <a href="/cgi-bin/koha/catalogue/MARCdetail.pl?biblionumber=[% biblionumber %]">Vista MARC en el catálogo</a></li>
 <li> <a href="/cgi-bin/koha/catalogue/ISBDdetail.pl?biblionumber=[% biblionumber %]">Vista ISBD en el catálogo</a></li>
</ul>