<script type="text/javascript">
//<![CDATA[
var MSG_ADDITEM_JS_ADDITEM = _("Agregar ítem");
var MSG_ADDITEM_JS_UPDATEITEM = _("Actualizar item");
var MSG_ADDITEM_JS_EDIT = _("Editar");
var MSG_ADDITEM_JS_DELETE = _("Eliminar");
var MSG_ADDITEM_JS_CLEAR = _("Borrar");
var MSG_ADDITEM_JS_CANT_RECEIVE_MORE_ITEMS = _("Usted no puede recibir más ítems ");
var MSG_ADDITEM_JS_IS_DUPLICATE = _("es duplicado");
var MSG_ADDITEM_JS_ALREADY_EXISTS_IN_DB = _("ya existe en la base de datos");
//]]>
</script>
