<tfoot>
 <tr>
 <td colspan="6" style="text-align: right; font-weight:bold;">Totales:</td>
 <td>[% totaldue %]</td>
 <td>[% totalprice %]</td>
 <td colspan="2">
 <p>Vencimiento de renovación: <input type="text" size="8" id="newduedate" name="newduedate" value="[% newduedate %]" />
</p>
 <p><label>Perdonar multas en la devolución: <input type="checkbox" name="exemptfine" value="1" /></label></p>
 </td>
 </tr>
</tfoot>
