<h5>Ejecutar informes</h5>
<ul>
 [% IF ( CAN_user_reports_execute_reports ) %]<li><a href="/cgi-bin/koha/reports/guided_reports.pl?phase=Use%20saved">Informes guardados</a></li>[% END %] </ul>
<h5>Diccionario de informes</h5>
<ul>
<li><a href="/cgi-bin/koha/reports/dictionary.pl?phase=View%20Dictionary">Ver diccionario</a></li>
</ul>
<h5>Recursos útiles</h5>
<ul>
<li><a href="http://wiki.koha-community.org/wiki/SQL_Reports_Library" target="blank">Biblioteca de informes Koha</a></li>
<li><a href="http://schema.koha-community.org/" target="blank">Esquema de base de datos de Koha</a></li>
</ul>
