<div id="toolbar" class="btn-toolbar">
 <div class="btn-group">
 <a class="btn btn-small" href="/cgi-bin/koha/labels/label-edit-layout.pl?op=new">Nuevo diseño</a>
 </div>

 <div class="btn-group">
 <a class="btn btn-small" href="/cgi-bin/koha/labels/label-edit-template.pl?op=new">Nueva plantilla</a>
 </div>

 <div class="btn-group">
 <a class="btn btn-small" href="/cgi-bin/koha/labels/label-edit-profile.pl?op=new">Nuevo perfil</a>
 </div>

 <div class="btn-group">
 <a class="btn btn-small" href="/cgi-bin/koha/labels/label-edit-batch.pl?op=new">Nuevo lote</a>
 </div>
</div>