<div id="navmenu"><ul id="navmenulist">
 <li><a href="/cgi-bin/koha/labels/label-home.pl">Etiquetas </a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=layout">Administrar diseños</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=template">Administrar plantillas</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=profile">Administrar perfiles</a></li>
 <li><a href="/cgi-bin/koha/labels/label-manage.pl?label_element=batch">Administrar lotes</a></li>
</ul>
</div>
