<div id="navmenu"><ul id="navmenulist">
 <li><a href="/cgi-bin/koha/patroncards/home.pl">Creador de carnet de usuario</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=layout">Administrar diseños</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=template">Administrar plantillas</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=profile">Administrar perfiles</a></li>
 <li><a href="/cgi-bin/koha/patroncards/manage.pl?card_element=batch">Administrar lotes</a></li>
 <li><a href="/cgi-bin/koha/patroncards/image-manage.pl">Administrar imágenes</a></li>
</ul>
</div>
