<div id="toolbar" class="btn-toolbar">
 <div class="btn-group"><a class="btn btn-small" id="add_quote" href="#"><i class="icon-plus"></i> Agregar cita</a></div>
 <div class="btn-group"><a class="btn btn-small" id="delete_quote" href="#"><i class="icon-remove"></i> Eliminar Comilla(s)</a></div>
 <div class="btn-group"><a class="btn btn-small" id="import_quotes" href="/cgi-bin/koha/tools/quotes-upload.pl"><i class="icon-folder-open"></i> Import quotes</a></div>
</div>