<h5>Informes guiados</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/guided_reports.pl">Informes guiados</a></li>
 </ul>

<h5>Estadísticas Compuestas</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">Adquisiciones</a></li>
 <li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">Usuarios</a></li>
 <li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">Catálogo</a></li>
 <li><a href="/cgi-bin/koha/reports/issues_stats.pl">Circulación</a></li>
 <li><a href="/cgi-bin/koha/reports/serials_stats.pl">Publicaciones periódicas</a></li>
 <li><a href="/cgi-bin/koha/reports/reserves_stats.pl">Reservas</a></li> 
 </ul>


 <h5>Listas principales</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Usuarios con más préstamos</a></li>
 <li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">Ítems más prestados</a></li>
 </ul>
 
 <h5>Inactivo</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/borrowers_out.pl">Usuarios que no han pedido prestado</a></li>
 <li><a href="/cgi-bin/koha/reports/catalogue_out.pl">Ítems nunca prestados</a></li>
 </ul>


 <h5>Otro</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/itemslost.pl">Ítems perdidos</a></li>
 <li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Catálogo por tipo de ítem</a></li>
 <li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">Tiempo de préstamo promedio</a></li>
 </ul>
