<h5>Guided reports</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/guided_reports.pl">Guided reports</a></li>
 </ul>

<h5>Estado</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/acquisitions_stats.pl">Adquisiciones</a></li>
 <li><a href="/cgi-bin/koha/reports/borrowers_stats.pl">Socios</a></li>
 <li><a href="/cgi-bin/koha/reports/catalogue_stats.pl">Catálogo</a></li>
 <li><a href="/cgi-bin/koha/reports/issues_stats.pl">Circulación</a></li>
 <li><a href="/cgi-bin/koha/reports/serials_stats.pl">Publicaciones periódicas</a></li>
 <li><a href="/cgi-bin/koha/reports/reserves_stats.pl">Reservas</a></li> 
 </ul>


 <h5>Top lists</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/bor_issues_top.pl">Socios con más préstamos</a></li>
 <li><a href="/cgi-bin/koha/reports/cat_issues_top.pl">Most-circulated items</a></li>
 </ul>
 
 <h5>Inactivo</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/borrowers_out.pl">Socios que no han pedido nada prestado</a></li>
 <li><a href="/cgi-bin/koha/reports/catalogue_out.pl">Ítems nunca prestados</a></li>
 </ul>


 <h5>Otro</h5>
 <ul>
 <li><a href="/cgi-bin/koha/reports/itemslost.pl">Lost items</a></li>
 <li><a href="/cgi-bin/koha/reports/manager.pl?report_name=itemtypes">Catalog by item type</a></li>
 <li><a href="/cgi-bin/koha/reports/issues_avg_stats.pl">Período promedio de préstamo</a></li>
 </ul>
